name: Docker Image Size

on:
  pull_request:
    branches:
      - main

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate sizes
        id: calc_sizes
        run: |
          BEFORE_SIZE=$(docker images | grep '<image_name>' | awk '{print $7$8}')
          AFTER_SIZE=$(docker images | grep '<image_name>' | awk '{print $7$8}')
          DIFFERENCE=$(expr $AFTER_SIZE - $BEFORE_SIZE)
          echo "::set-output name=before_size::$BEFORE_SIZE"
          echo "::set-output name=after_size::$AFTER_SIZE"
          echo "::set-output name=difference::$DIFFERENCE"

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = steps.calc_sizes.outputs
            const comment = `Before size: ${output.before_size}, After size: ${output.after_size}, Difference: ${output.difference}`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

      - name: Handle prow slash commands
        uses: jpmcb/prow-github-actions@v1
        with:
          prow-commands: |
            /approve
            /lgtm
          github-token: ${{ secrets.GITHUB_TOKEN }}
