name: Docker Image Size

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: app:latest

      - name: Calculate Docker image size
        id: calc-size
        run: |
          SIZE=$(docker image inspect app:latest --format='{{.Size}}')
          echo "size=$SIZE" >> "$GITHUB_OUTPUT"

      - name: Check if .prev_size file exists
        run: |
          if [ ! -f .prev_size ]; then
            echo "0" > .prev_size
          fi

      - name: Calculate size difference
        id: calc-diff
        run: |
          PREV_SIZE=$(cat .prev_size)
          SIZE=${{steps.calc-size.outputs.size}}
          DIFF=$(bc <<< "$SIZE - $PREV_SIZE")

          echo "Difference: ${DIFF} bytes"
          echo "::set-output name=diff::$DIFF"

      - name: Convert size difference to human-readable format
        id: convert-diff
        run: |
          DIFF=${{steps.calc-diff.outputs.diff}}
          HUMAN_DIFF=$(numfmt --to=iec-i --suffix=B --format="%.1f" $DIFF)
      
          echo "Human-readable difference: ${HUMAN_DIFF}"
          echo "::set-output name=human_diff::$HUMAN_DIFF"
      
      
      
      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          COMMENT="The Docker image size difference is ${{ steps.convert-diff.outputs.human_diff }}."
          echo "$COMMENT" | gh pr comment "$PR_NUM" --body-file=-

      - name: Update previous size
        run: |
          echo "${{ steps.calc-size.outputs.size }}" > .prev_size
