name: Docker Image Size

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build main branch Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: app:main

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: app:latest

      - name: Calculate Docker image size
        id: calc-size
        run: |
          BEFORE_SIZE=$(docker image inspect app:main --format='{{.Size}}')
          AFTER_SIZE=$(docker image inspect app:latest --format='{{.Size}}')
          echo "before_size=$BEFORE_SIZE" >> "$GITHUB_OUTPUT"
          echo "after_size=$AFTER_SIZE" >> "$GITHUB_OUTPUT"

      - name: Check if .prev_size file exists
        run: |
          if [ ! -f .prev_size ]; then
            echo "0" > .prev_size
          fi

      - name: Calculate size difference
        id: calc-diff
        run: |
          BEFORE_SIZE=${{steps.calc-size.outputs.before_size}}
          AFTER_SIZE=${{steps.calc-size.outputs.after_size}}
          DIFF=$(bc <<< "$AFTER_SIZE - $BEFORE_SIZE")

          echo "Difference: ${DIFF} bytes"
          echo "::set-output name=diff::$DIFF"

      - name: Convert size difference to human-readable format
        id: convert-diff
        run: |
          DIFF=${{steps.calc-diff.outputs.diff}}
          HUMAN_DIFF=$(numfmt --to=iec-i --suffix=B --format="%.1f" $DIFF)

          echo "Human-readable difference: ${HUMAN_DIFF}"
          echo "::set-output name=human_diff::$HUMAN_DIFF"

      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          gh pr comment "$PR_NUM" --body "| Docker image size difference | Before size | After size |
          | --- | --- | --- |
          | ${{ steps.convert-diff.outputs.human_diff }} | ${{ steps.calc-size.outputs.before_size }} | ${{ steps.calc-size.outputs.after_size }} |"

      - name: Update previous size
        run: |
          echo "${{ steps.calc-size.outputs.size }}" > .prev_size
