name: Prow Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  prow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Prow Commands
        uses: kubernetes/test-infra/prow-github-actions@v1
        with:
          command: 'lgtm,approve'
          token: ${{ secrets.GITHUB_TOKEN }}
